mvnw

diff --git a/week2_exercises/16.Creating a spring Boot Application/LibraryManagement/mvnw b/week2_exercises/16.Creating a spring Boot Application/LibraryManagement/mvnw
--- a/week2_exercises/16.Creating a spring Boot Application/LibraryManagement/mvnw
+++ b/week2_exercises/16.Creating a spring Boot Application/LibraryManagement/mvnw
@@ -1,1 +1,112 @@
-a
+#!/bin/sh
+# ----------------------------------------------------------------------------
+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements. See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License. You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+# ----------------------------------------------------------------------------
+
+# ----------------------------------------------------------------------------
+# Maven2 Start Up Batch script
+#
+# Required ENV vars:
+# JAVA_HOME - location of a JDK home dir
+#
+# Optional ENV vars
+# M2_HOME - location of maven2's installed home dir
+# MAVEN_OPTS - parameters passed to the Java VM when running Maven
+#     e.g. to debug Maven itself, use
+# set MAVEN_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000
+# MAVEN_SKIP_RC - flag to disable loading of mavenrc files
+# ----------------------------------------------------------------------------
+
+if [ -z "$MAVEN_SKIP_RC" ] ; then
+
+  if [ -f /etc/mavenrc ] ; then
+    . /etc/mavenrc
+  fi
+
+  if [ -f "$HOME/.mavenrc" ] ; then
+    . "$HOME/.mavenrc"
+  fi
+
+fi
+
+# OS specific support (must be 'true' or 'false').
+cygwin=false
+msys=false
+darwin=false
+case "`uname`" in
+  CYGWIN*) cygwin=true ;;
+  MINGW*) msys=true ;;
+  Darwin*) darwin=true
+           # Use /usr/libexec/java_home if available, otherwise fall back to /Library/Java/Home
+           if [ -z "$JAVA_HOME" ] ; then
+             if [ -x '/usr/libexec/java_home' ] ; then
+               JAVA_HOME=`/usr/libexec/java_home`
+             else
+               JAVA_HOME=/Library/Java/Home
+             fi
+           fi
+           ;;
+esac
+
+if [ -z "$JAVA_HOME" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly."
+  echo "  We cannot execute $JAVA_HOME/bin/java"
+  exit 1
+fi
+
+if [ "$cygwin" = "true" ] ; then
+  [ -n "$M2_HOME" ] &&
+    M2_HOME=`cygpath --unix "$M2_HOME"`
+  [ -n "$JAVA_HOME" ] &&
+    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+fi
+
+if [ -z "$M2_HOME" ] ; then
+  if [ -r /usr/local/apache-maven/apache-maven-3.6.3 ] ; then
+    M2_HOME=/usr/local/apache-maven/apache-maven-3.6.3
+  elif [ -r /usr/local/apache-maven ] ; then
+    M2_HOME=/usr/local/apache-maven
+  else
+    M2_HOME=`cd -P "$PRGDIR/.." && pwd -P`
+  fi
+fi
+
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] &&
+    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$M2_HOME" ] &&
+    M2_HOME=`cygpath --unix "$M2_HOME"`
+  [ -n "$MAVEN_OPTS" ] &&
+    MAVEN_OPTS=`cygpath --path --unix "$MAVEN_OPTS"`
+fi
+
+CLASSWORLDS_LAUNCHER=$M2_HOME/lib/maven-artifact-transfer-0.12.0.jar
+
+# For Darwin, add options to specify correct Apple JDK for Maven
+if $darwin ; then
+  MAVEN_OPTS="$MAVEN_OPTS -Djava.library.path=$JAVA_HOME/../Libraries"
+fi
+
+export MAVEN_OPTS
+
+exec "$JAVA_HOME/bin/java" \
+  -classpath "$CLASSWORLDS_LAUNCHER" \
+  "-Dclassworlds.conf=$M2_HOME/bin/m2.conf" \
+  "-Dmaven.home=$M2_HOME" \
+  "-Dmaven.multiModuleProjectDirectory=$MAVEN_PROJECTBASEDIR" \
+  $MAVEN_OPTS \
+  org.codehaus.plexus.classworlds.launcher.Launcher "$@"
